// Mock data for development - replace with real API calls later
import type {
  EventRecord,
  Invitation,
  AttendanceLog,
  HostStats,
} from "./types";

export const mockUser = {
  id: "local-user-123",
  email: "host@example.com",
  user_metadata: {
    display_name: "Event Host",
  },
};

export const mockEvents: EventRecord[] = [
  {
    id: 1,
    user_id: mockUser.id,
    title: "Summer Gala 2024",
    description: "An elegant evening celebrating the start of summer",
    venue: "Grand Ballroom",
    address: "123 Event Avenue, City Center",
    starts_at: new Date(Date.now() + 86400000).toISOString(), // Tomorrow
    ends_at: new Date(Date.now() + 90000000).toISOString(),
    capacity: 150,
    dress_code: "Black Tie",
    cover_image: "/covers/gala.jpg",
    status: "published",
    created_at: new Date().toISOString(),
    guest_count: 45,
    checked_in_count: 28,
    accepted_count: 45,
    declined_count: 5,
  },
  {
    id: 2,
    user_id: mockUser.id,
    title: "Tech Meetup",
    description: "Monthly tech community gathering",
    venue: "Innovation Hub",
    address: "456 Tech Street",
    starts_at: new Date(Date.now() + 172800000).toISOString(), // In 2 days
    ends_at: new Date(Date.now() + 176400000).toISOString(),
    capacity: 100,
    dress_code: "Business Casual",
    cover_image: "/covers/tech.jpg",
    status: "published",
    created_at: new Date().toISOString(),
    guest_count: 32,
    checked_in_count: 18,
    accepted_count: 32,
    declined_count: 3,
  },
  {
    id: 3,
    user_id: mockUser.id,
    title: "Charity Dinner",
    description: "Annual fundraiser for local community",
    venue: "Downtown Restaurant",
    address: "789 Charity Lane",
    starts_at: new Date(Date.now() - 86400000).toISOString(), // Yesterday
    ends_at: new Date(Date.now() - 82800000).toISOString(),
    capacity: 200,
    dress_code: "Formal",
    cover_image: "/covers/charity.jpg",
    status: "published",
    created_at: new Date(Date.now() - 604800000).toISOString(),
    guest_count: 85,
    checked_in_count: 82,
    accepted_count: 85,
    declined_count: 2,
  },
];

export const mockInvitations: Invitation[] = [
  {
    id: 1,
    event_id: 1,
    guest_name: "John Smith",
    guest_email: "john@example.com",
    guest_phone: "+1-555-0101",
    plus_ones: 1,
    status: "checked_in",
    qr_token: "qr_token_1",
    note: "VIP Guest",
    checked_in_at: new Date(Date.now() - 3600000).toISOString(),
    created_at: new Date(Date.now() - 604800000).toISOString(),
  },
  {
    id: 2,
    event_id: 1,
    guest_name: "Sarah Johnson",
    guest_email: "sarah@example.com",
    guest_phone: "+1-555-0102",
    plus_ones: 0,
    status: "accepted",
    qr_token: "qr_token_2",
    note: "",
    checked_in_at: null,
    created_at: new Date(Date.now() - 604800000).toISOString(),
  },
  {
    id: 3,
    event_id: 1,
    guest_name: "Michael Chen",
    guest_email: "michael@example.com",
    guest_phone: "+1-555-0103",
    plus_ones: 2,
    status: "pending",
    qr_token: "qr_token_3",
    note: "Bringing family",
    checked_in_at: null,
    created_at: new Date(Date.now() - 604800000).toISOString(),
  },
  {
    id: 4,
    event_id: 1,
    guest_name: "Emma Wilson",
    guest_email: "emma@example.com",
    guest_phone: "+1-555-0104",
    plus_ones: 0,
    status: "declined",
    qr_token: "qr_token_4",
    note: "Out of town",
    checked_in_at: null,
    created_at: new Date(Date.now() - 604800000).toISOString(),
  },
];

export const mockAttendanceLogs: AttendanceLog[] = [
  {
    id: 1,
    invitation_id: 1,
    event_id: 1,
    result: "success",
    guest_name: "John Smith",
    scanned_by: "admin",
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 2,
    invitation_id: null,
    event_id: 1,
    result: "invalid",
    guest_name: "Unknown Guest",
    scanned_by: "admin",
    created_at: new Date(Date.now() - 3300000).toISOString(),
  },
  {
    id: 3,
    invitation_id: 2,
    event_id: 1,
    result: "duplicate",
    guest_name: "Sarah Johnson",
    scanned_by: "admin",
    created_at: new Date(Date.now() - 3000000).toISOString(),
  },
];

export const mockStats: HostStats = {
  guest_count: 85,
  checked_in_count: 28,
  accepted_count: 82,
  declined_count: 3,
  pending_count: 7,
  sent_count: 92,
  plus_ones: 15,
  event_count: 3,
  active_events: 2,
};
